# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'widgets.ui'
##
## Created by: Qt User Interface Compiler version 6.2.3
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QAbstractButton, QApplication, QCheckBox, QComboBox,
    QDateEdit, QDateTimeEdit, QDial, QDialogButtonBox,
    QDoubleSpinBox, QFrame, QGroupBox, QLabel,
    QLineEdit, QPlainTextEdit, QPushButton, QRadioButton,
    QSizePolicy, QSlider, QSpinBox, QTabWidget,
    QTimeEdit, QWidget)

class Ui_Form(object):
    def setupUi(self, Form):
        if not Form.objectName():
            Form.setObjectName(u"Form")
        Form.resize(643, 781)
        self.buttonBox = QDialogButtonBox(Form)
        self.buttonBox.setObjectName(u"buttonBox")
        self.buttonBox.setGeometry(QRect(400, 730, 156, 23))
        self.buttonBox.setOrientation(Qt.Horizontal)
        self.buttonBox.setStandardButtons(QDialogButtonBox.Cancel|QDialogButtonBox.Ok)
        self.comboBox = QComboBox(Form)
        self.comboBox.setObjectName(u"comboBox")
        self.comboBox.setGeometry(QRect(190, 460, 171, 22))
        self.tabWidget = QTabWidget(Form)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabWidget.setGeometry(QRect(110, 240, 421, 211))
        self.tab = QWidget()
        self.tab.setObjectName(u"tab")
        sizePolicy = QSizePolicy(QSizePolicy.Preferred, QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tab.sizePolicy().hasHeightForWidth())
        self.tab.setSizePolicy(sizePolicy)
        self.groupBox_4 = QGroupBox(self.tab)
        self.groupBox_4.setObjectName(u"groupBox_4")
        self.groupBox_4.setGeometry(QRect(294, 9, 81, 165))
        self.d1F = QRadioButton(self.groupBox_4)
        self.d1F.setObjectName(u"d1F")
        self.d1F.setGeometry(QRect(10, 23, 61, 17))
        self.d1F.setChecked(True)
        self.d2F = QRadioButton(self.groupBox_4)
        self.d2F.setObjectName(u"d2F")
        self.d2F.setGeometry(QRect(10, 46, 61, 17))
        self.d3F = QRadioButton(self.groupBox_4)
        self.d3F.setObjectName(u"d3F")
        self.d3F.setGeometry(QRect(10, 69, 61, 17))
        self.d4F = QRadioButton(self.groupBox_4)
        self.d4F.setObjectName(u"d4F")
        self.d4F.setGeometry(QRect(10, 90, 61, 17))
        self.d5F = QRadioButton(self.groupBox_4)
        self.d5F.setObjectName(u"d5F")
        self.d5F.setGeometry(QRect(10, 115, 61, 17))
        self.d6F = QRadioButton(self.groupBox_4)
        self.d6F.setObjectName(u"d6F")
        self.d6F.setGeometry(QRect(10, 138, 61, 17))
        self.groupBox_6 = QGroupBox(self.tab)
        self.groupBox_6.setObjectName(u"groupBox_6")
        self.groupBox_6.setGeometry(QRect(9, 9, 220, 161))
        self.line2 = QLineEdit(self.groupBox_6)
        self.line2.setObjectName(u"line2")
        self.line2.setGeometry(QRect(77, 77, 133, 20))
        self.check3 = QCheckBox(self.groupBox_6)
        self.check3.setObjectName(u"check3")
        self.check3.setGeometry(QRect(10, 118, 61, 17))
        self.check1 = QCheckBox(self.groupBox_6)
        self.check1.setObjectName(u"check1")
        self.check1.setGeometry(QRect(10, 38, 61, 17))
        self.check1.setChecked(True)
        self.check2 = QCheckBox(self.groupBox_6)
        self.check2.setObjectName(u"check2")
        self.check2.setGeometry(QRect(10, 78, 61, 17))
        self.line1 = QLineEdit(self.groupBox_6)
        self.line1.setObjectName(u"line1")
        self.line1.setGeometry(QRect(77, 37, 133, 20))
        self.line3 = QLineEdit(self.groupBox_6)
        self.line3.setObjectName(u"line3")
        self.line3.setGeometry(QRect(77, 117, 133, 20))
        self.tabWidget.addTab(self.tab, "")
        self.label = QLabel(Form)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(80, 740, 161, 20))
        self.label_6 = QLabel(Form)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(30, 520, 141, 20))
        self.label_6.setLayoutDirection(Qt.RightToLeft)
        self.label_6.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.label_9 = QLabel(Form)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(30, 590, 301, 20))
        self.label_9.setLayoutDirection(Qt.RightToLeft)
        self.label_9.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.spinBox = QSpinBox(Form)
        self.spinBox.setObjectName(u"spinBox")
        self.spinBox.setGeometry(QRect(220, 10, 311, 20))
        self.label_3 = QLabel(Form)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(20, 40, 181, 20))
        self.label_3.setLayoutDirection(Qt.RightToLeft)
        self.label_3.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.timeEdit = QTimeEdit(Form)
        self.timeEdit.setObjectName(u"timeEdit")
        self.timeEdit.setGeometry(QRect(190, 520, 118, 22))
        self.plainTextEdit = QPlainTextEdit(Form)
        self.plainTextEdit.setObjectName(u"plainTextEdit")
        self.plainTextEdit.setGeometry(QRect(190, 490, 291, 21))
        self.dateEdit = QDateEdit(Form)
        self.dateEdit.setObjectName(u"dateEdit")
        self.dateEdit.setGeometry(QRect(420, 520, 110, 22))
        self.label_2 = QLabel(Form)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(20, 10, 181, 20))
        self.label_2.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.label_5 = QLabel(Form)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(20, 490, 151, 20))
        self.label_5.setLayoutDirection(Qt.RightToLeft)
        self.label_5.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.label_7 = QLabel(Form)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(330, 520, 81, 20))
        self.label_7.setLayoutDirection(Qt.RightToLeft)
        self.label_7.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.dateTimeEdit = QDateTimeEdit(Form)
        self.dateTimeEdit.setObjectName(u"dateTimeEdit")
        self.dateTimeEdit.setGeometry(QRect(190, 550, 194, 22))
        self.label_8 = QLabel(Form)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(30, 550, 141, 20))
        self.label_8.setLayoutDirection(Qt.RightToLeft)
        self.label_8.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.doubleSpinBox = QDoubleSpinBox(Form)
        self.doubleSpinBox.setObjectName(u"doubleSpinBox")
        self.doubleSpinBox.setGeometry(QRect(220, 40, 311, 20))
        self.frame = QFrame(Form)
        self.frame.setObjectName(u"frame")
        self.frame.setGeometry(QRect(110, 70, 421, 161))
        self.frame.setFrameShape(QFrame.StyledPanel)
        self.frame.setFrameShadow(QFrame.Raised)
        self.dial = QDial(self.frame)
        self.dial.setObjectName(u"dial")
        self.dial.setGeometry(QRect(10, 10, 100, 100))
        self.horizontalSlider = QSlider(self.frame)
        self.horizontalSlider.setObjectName(u"horizontalSlider")
        self.horizontalSlider.setGeometry(QRect(116, 69, 161, 22))
        self.horizontalSlider.setOrientation(Qt.Horizontal)
        self.verticalSlider = QSlider(self.frame)
        self.verticalSlider.setObjectName(u"verticalSlider")
        self.verticalSlider.setGeometry(QRect(330, 20, 22, 131))
        self.verticalSlider.setOrientation(Qt.Vertical)
        self.label_4 = QLabel(Form)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(20, 460, 151, 20))
        self.label_4.setLayoutDirection(Qt.RightToLeft)
        self.label_4.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.groupBox = QGroupBox(Form)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setGeometry(QRect(90, 630, 451, 80))
        self.pushButton = QPushButton(self.groupBox)
        self.pushButton.setObjectName(u"pushButton")
        self.pushButton.setGeometry(QRect(30, 30, 111, 31))
        self.checkBox = QCheckBox(self.groupBox)
        self.checkBox.setObjectName(u"checkBox")
        self.checkBox.setGeometry(QRect(170, 30, 91, 31))
        self.lineEdit = QLineEdit(self.groupBox)
        self.lineEdit.setObjectName(u"lineEdit")
        self.lineEdit.setGeometry(QRect(280, 30, 113, 20))

        self.retranslateUi(Form)

        self.tabWidget.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(Form)
    # setupUi

    def retranslateUi(self, Form):
        Form.setWindowTitle(QCoreApplication.translate("Form", u"Form", None))
        self.groupBox_4.setTitle(QCoreApplication.translate("Form", u"Radio Buttons", None))
        self.d1F.setText(QCoreApplication.translate("Form", u"B1", None))
        self.d2F.setText(QCoreApplication.translate("Form", u"B2", None))
        self.d3F.setText(QCoreApplication.translate("Form", u"B3", None))
        self.d4F.setText(QCoreApplication.translate("Form", u"B4", None))
        self.d5F.setText(QCoreApplication.translate("Form", u"B5", None))
        self.d6F.setText(QCoreApplication.translate("Form", u"B6", None))
        self.groupBox_6.setTitle(QCoreApplication.translate("Form", u"Values", None))
        self.check3.setText(QCoreApplication.translate("Form", u"Check 3", None))
        self.check1.setText(QCoreApplication.translate("Form", u"Check 1", None))
        self.check2.setText(QCoreApplication.translate("Form", u"Check 2", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QCoreApplication.translate("Form", u"Tab Widget", None))
        self.label.setText(QCoreApplication.translate("Form", u"LABEL", None))
        self.label_6.setText(QCoreApplication.translate("Form", u"TIME EDIT", None))
        self.label_9.setText(QCoreApplication.translate("Form", u"KEY SEQUENCE EDIT NOT SUPPORTED", None))
        self.label_3.setText(QCoreApplication.translate("Form", u"DOUBLE SPINBOX", None))
        self.label_2.setText(QCoreApplication.translate("Form", u"SPINBOX", None))
        self.label_5.setText(QCoreApplication.translate("Form", u"PLAIN TEXT EDIT", None))
        self.label_7.setText(QCoreApplication.translate("Form", u"DATE EDIT", None))
        self.label_8.setText(QCoreApplication.translate("Form", u"DATE/TIME EDIT", None))
        self.label_4.setText(QCoreApplication.translate("Form", u"COMBO BOX", None))
        self.groupBox.setTitle(QCoreApplication.translate("Form", u"GroupBox", None))
        self.pushButton.setText(QCoreApplication.translate("Form", u"PushButton", None))
        self.checkBox.setText(QCoreApplication.translate("Form", u"CheckBox", None))
    # retranslateUi

